name: "Run Buck"
description: "Run Buck from GitHub Actions"
inputs:
  commands:
    description: "Semicolon-separated commands to run"
    required: true
    default: echo "No commands executed"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.commands }}
